jobs:
  enforce-label:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: yogevbd/enforce-label-action@2.2.2
      with:
        REQUIRED_LABELS_ANY: bug,enhancement,internal,no-changelog
        REQUIRED_LABELS_ANY_DESCRIPTION: Select at least one label ['bug','enhancement','internal','no-changelog']
          for the PR
name: Enforce PR labels for release drafter
on:
  repository_dispatch:
    types: trigger-ga___enforce-labels.yml
